// utils/data.js
export const data = {
  products: [
    {
      id: '1',
      name: 'Pink Polo Shirt',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 57,
      description: 'high quality shirt',
    },
    {
      id: '2',
      name: 'Marl Polo Shirt',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      rating: 4.0,
      numReviews: 74,
      description: 'high quality product',
    },
    {
      id: '3',
      name: 'Slim Fit Polo Shirt',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      id: '4',
      name: 'Orange Polo Shirt',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 39,
      description: 'high quality product',
    },
    {
      id: '5',
      name: 'Black Polo Shirt',
      image: '/images/p5.jpg',
      price: 85,
      countInStock: 5,
      rating: 4.0,
      numReviews: 84,
      description: 'high quality product',
    },
    {
      id: '6',
      name: 'Tan Polo Slim-fitted Shirt',
      image: '/images/p6.jpg',
      price: 185,
      countInStock: 5,
      rating: 3.5,
      numReviews: 57,
      description: 'high quality product',
    },
    {
      id: '7',
      name: 'Beige Polo Shirt',
      image: '/images/p7.jpg',
      price: 60,
      countInStock: 5,
      rating: 4.7,
      numReviews: 120,
      description: 'high quality product',
    },
    {
      id: '8',
      name: 'Purple Polo Shirt',
      image: '/images/p8.jpg',
      price: 15,
      countInStock: 5,
      rating: 4.8,
      numReviews: 18,
      description: 'high quality product',
    },
  ],
};
